services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: production
    volumes:
      - laravel_storage:/var/www/html/storage
    environment:
      PHP_OPCACHE_ENABLE: 1

  db:
    image: mariadb:10.6
    command: --wait-timeout=${MYSQL_WAIT_TIMEOUT:-120} --interactive-timeout=${MYSQL_WAIT_TIMEOUT:-120}
    env_file: ./.env
    environment:
      TZ: ${TZ:-Asia/Manila}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
    volumes:
      - dbdata:/var/lib/mysql
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost", "-u", "root", "-p${MYSQL_ROOT_PASSWORD}" ]
      interval: 5s
      timeout: 3s
      retries: 10
      start_period: 30s

  phpmyadmin:
    image: phpmyadmin
    environment:
      PMA_HOST: ${MYSQL_HOST}
      PMA_USER: ${MYSQL_USER}
      PMA_PASSWORD: ${MYSQL_PASSWORD}

volumes:
  dbdata:
  laravel_storage:
